version: 2.1
jobs:
  build:
    docker:
    - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: pip install --upgrade pip
      - run: sudo pip install jupyter_client
      - run: sudo pip install nbconvert
      - run: sudo pip install requests
      - run: sudo pip install bs4
      - run: sudo pip install random
      - run: sudo pip install pillow
      - run: sudo python3 -m pip install ipykernel
      - run: sudo python3 -m ipykernel install --user
      - run: jupyter nbconvert --execute ./picscraper.ipynb --to html
      - store_artifacts:
          path: ./Notebook.html
          destination:  Notebook.html
          